language: python

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560 examples/SimpleModbus/SimpleModbus.ino
